[package]
name = "rust_nx"
version = "0.1.0"
edition = "2021"
authors = ["not-ebx"]
description = "A NX-type file reader, for mushroom game. Implements the PKNX4 format"
repository = "https://github.com/not-ebx/rustNX"
license = "MIT"

[dependencies]
byteorder = "1.5.0"